---
vms:
- name: master.a.dnc.example
  box: puppetlabs/centos-7.0-64-nocm
  roles:
  - pe-puppet-master
- name: master.b.dnc.example
  box: puppetlabs/centos-7.0-64-nocm
  roles:
  - pe-puppet-master
- name: agent1.b.dnc.example
  box: puppetlabs/centos-7.0-64-nocm
  roles:
  - pe-puppet-agent
